/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('filmes').del()
  await knex('filmes').insert([
    { title: "Airplane!", year: 1980, cast: "Robert Hays", genre: "Comedy", href: "Airplane!", extract: "Airplane! is a 1980 American parody film written and directed by the brothers David and Jerry Zucker, and Jim Abrahams in their directorial debuts, and produced by Jon Davison. It stars Robert Hays and Julie Hagerty and features Leslie Nielsen, Robert Stack, Lloyd Bridges, Peter Graves, Kareem Abdul-Jabbar, and Lorna Patterson. It is a parody of the disaster film genre, particularly the 1957 Paramount film Zero Hour!, from which it borrows its plot, central characters, and some dialogue. It also draws many elements from Airport 1975 and other films in the Airport series. It is known for its use of surreal humor and fast-paced slapstick comedy, including visual and verbal puns, gags, running jokes, and obscure humor.", thumbnail: "https://upload.wikimedia.org/wikipedia/en/2/21/Airplane%21_%281980_film%29.jpg", thumbnail_width: 258, thumbnail_height: 386},
    { title: "Alex and the Doberman Gang", year: 1980, cast: "Jack Stauffer", genre: "Action", "href": null, extract: null, thumbnail: null, thumbnail_width: null, thumbnail_height: null},
    { title: "Alien Dead", year: 1980, cast: "Buster Crabbe", genre: "Science Fiction", href: "Alien_Dead", extract: "Alien Dead is an American horror film directed by Fred Olen Ray. Ray co-wrote the script with Martin Nicholas. The film involves a meteor hitting a houseboat, which causes the people on board to become zombies who eat alligators and eventually people.", thumbnail: "https://upload.wikimedia.org/wikipedia/en/8/8f/Aliendeaddvd.jpg", thumbnail_width: 272, thumbnail_height: 384 },
    { title: "Alligator", year: 1980, cast: "Robert Forster", genre: "Horror", href: "Alligator_(film)", extract: "Alligator is a 1980 American independent horror film directed by Lewis Teague and written by John Sayles. It stars Robert Forster, Robin Riker and Michael V. Gazzo. It also includes an appearance by actress Sue Lyon in her last screen role. Set in Chicago, the film follows a police officer and a reptile expert who track an enormous, ravenous man-eating alligator flushed down the toilet years earlier, that is attacking residents after escaping from the city’s sewers.", thumbnail: "https://upload.wikimedia.org/wikipedia/en/c/c9/Alligator_poster.jpg", thumbnail_width: 241, thumbnail_height: 366},
    { title: "The Attic", year: 1980, cast: "Carrie Snodgress", genre: "Horror", href: "The_Attic_(1980_film)", extract: "The Attic is a 1980 American psychological horror drama film directed by George Edwards and starring Carrie Snodgress and Ray Milland.", thumbnail: "https://upload.wikimedia.org/wikipedia/en/5/59/The_Attic_%281980_poster%29.jpg", thumbnail_width: 253, thumbnail_height: 394 },
    { title: "The Awakening", year: 1980, cast: "Charlton Heston", genre: "Horror", href: "The_Awakening_(1980_film)", extract: "The Awakening is a 1980 British horror film directed by Mike Newell in his directorial debut and starring Charlton Heston, Susannah York, and Stephanie Zimbalist. It is the third film version of Bram Stoker's 1903 novel The Jewel of Seven Stars, following the 1970 television adaptation as The Curse of the Mummy for the TV series Mystery and Imagination, and the 1971 theatrical film by Hammer, Blood from the Mummy's Tomb. It was released by Warner Bros.", thumbnail: "https://upload.wikimedia.org/wikipedia/en/8/89/Awakeningposter1980.jpg", thumbnail_width: 254, thumbnail_height: 390 },
    { title: "The Baltimore Bullet", year: 1980, cast: "James Coburn", genre: "Comedy", href: "The_Baltimore_Bullet", extract: "The Baltimore Bullet is a 1979 American comedy film based on the adventures of two pool hustlers in the United States.", thumbnail: "https://upload.wikimedia.org/wikipedia/en/3/3c/Thebaltimorebullet_gip.jpg", thumbnail_width: 258, thumbnail_height: 387},
    { title: "The Big Brawl", year: 1980, cast: "Jackie Chan", genre: "Action", href: "The_Big_Brawl", extract: "The Big Brawl, also known as Battle Creek Brawl, is a 1980 martial arts action comedy film, which marked Jackie Chan's first attempt to break into the American movie Hollywood market. A joint American and Hong Kong action film production, it was directed by Robert Clouse and featured much of the crew from Enter the Dragon (1973).", thumbnail: "https://upload.wikimedia.org/wikipedia/en/b/bd/Bigbrawlposter.jpg", thumbnail_width: 257, thumbnail_height: 388},
    { title: "The Blue Lagoon", year: 1980, cast: "Brooke Shields", genre: "Adventure", href: "The_Blue_Lagoon_(1980_film)", extract: "The Blue Lagoon is a 1980 American dramatic coming-of-age romantic survival film directed by Randal Kleiser from a screenplay written by Douglas Day Stewart based on the 1908 novel of the same name by Henry De Vere Stacpoole. The film stars Brooke Shields and Christopher Atkins. The music score was composed by Basil Poledouris and the cinematography was by Néstor Almendros.", thumbnail: "https://upload.wikimedia.org/wikipedia/en/3/32/Blue_lagoon_1980_movie_poster.jpg", thumbnail_width: 255, thumbnail_height: 389},
    { title: "Cannibal Apocalypse", year: 1980, cast: "Elizabeth Turner", genre: "Horror", href: "Cannibal_Apocalypse", extract: "Cannibal Apocalypse is a 1980 action horror film directed by Antonio Margheriti and starring John Saxon, Elizabeth Turner, Giovanni Lombardo Radice, Cinzia De Carolis, Tony King and Ramiro Oliveros. The film combines the cannibal film genre with a forerunner of Margheriti's Vietnam War films.", thumbnail: "https://upload.wikimedia.org/wikipedia/en/e/ee/Cannibal_Apocalypse.jpg", thumbnail_width: 268, thumbnail_height: 373},
  ]);
};
